stages:
  - build
  - push
  - scan
  - code_quality
  - safety

variables:
  IMAGE_NAME: $HARBOR_HOST/library/$CI_PROJECT_NAME

build:
  image: docker:27.3.0
  stage: build
  services:
    - docker:27.3.0-dind
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

trivy_scan:
  stage: scan
  image: 
    name: aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy image --exit-code 1 --ignore-unfixed --severity HIGH,CRITICAL $IMAGE_NAME:$CI_COMMIT_REF_SLUG
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

code_quality:
  stage: code_quality
  image: python:3.12
  before_script:
    - pip install flake8
  script:
    - flake8 .
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

safety:
  stage: safety
  image: python:3.12
  before_script:
    - pip install safety
  script:
    - safety check
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

push:
  stage: push
  image: docker:27.3.0
  before_script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG -t $IMAGE_NAME:latest --push .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH