version: '3'
services:
    matrix-chatgpt-bot:
      restart: unless-stopped
      container_name: matrix-chatbot
      image: krim/matrixbot
      build:
          dockerfile: Dockerfile
      env_file:
        - ./env
      networks:
        - nginx
      volumes:
        - /srv/matrixbot:/opt/store
networks:
    nginx:
      external: true
